ssl = yes

# Certificados genéricos snakeoil gerados nativamente pelo Ubuntu
ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key

ssl_client_ca_dir = /etc/ssl/certs

# Linha comentada abaixo para evitar falhas de inicialização TLS (Arquivo inexistente no Ubuntu limpo)
#ssl_dh = </usr/share/dovecot/dh.pem

ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes