# Upstreams
upstream dsrjoaovitor1 {
    server site1:80;
}

upstream dsrjoaovitor2 {
    server site2:80;
}

upstream dsrjoaovitor3 {
    server site3:80;
}

# =========================
# DSRJOAOVITOR1
# =========================
server {
    listen 80;
    listen [::]:80;

    server_name dsrjoaovitor1.dsrjoaovitor.test;

    access_log /var/log/nginx/dsrjoaovitor1.access.log;
    error_log  /var/log/nginx/dsrjoaovitor1.error.log;

    location / {
        proxy_pass http://dsrjoaovitor1/;
    }
}

# =========================
# DSRJOAOVITOR2
# =========================
server {
    listen 80;
    listen [::]:80;

    server_name dsrjoaovitor2.dsrjoaovitor.test;

    access_log /var/log/nginx/dsrjoaovitor2.access.log;
    error_log  /var/log/nginx/dsrjoaovitor2.error.log;

    location / {
        proxy_pass http://dsrjoaovitor2/;
    }
}

# =========================
# DSRJOAOVITOR3
# =========================
server {
    listen 80;
    listen [::]:80;

    server_name dsrjoaovitor3.dsrjoaovitor.test;

    access_log /var/log/nginx/dsrjoaovitor3.access.log;
    error_log  /var/log/nginx/dsrjoaovitor3.error.log;

    location / {
        proxy_pass http://dsrjoaovitor3/;
    }
}

