# Upstreams
upstream jonastech {
    server site1:80;
}

upstream jonasredes {
    server site2:80;
}

upstream jonasti {
    server site3:80;
}

# =========================
# JONASTECH
# =========================

server {
    listen 80;
    listen [::]:80;

    server_name jonastech.jonaslab.test;

    access_log /var/log/nginx/jonastech.access.log;

    location / {
        proxy_pass http://jonastech;
    }
}

# =========================
# JONASREDES
# =========================

server {
    listen 80;
    listen [::]:80;

    server_name jonasredes.jonaslab.test;

    access_log /var/log/nginx/jonasredes.access.log;

    location / {
        proxy_pass http://jonasredes;
    }
}

# =========================
# JONASTI
# =========================

server {
    listen 80;
    listen [::]:80;

    server_name jonasti.jonaslab.test;

    access_log /var/log/nginx/jonasti.access.log;

    location / {
        proxy_pass http://jonasti;
    }
}